### ISSUE TITLE
Question about POS and NER in the model

### ISSUE THREAD

**Issue by nanonaren** [hitvoice/DrQA#10]
Does the model map each POS tag and NER tag category to a one-hot encoding? If not, why? It doesn't make sense to me how you can just supply the category ID directly in the embedding.

**Comment by hitvoice** [comment]
One hot encoding is currently used in the project. The previous versions (about half a year ago) used separate embeddings for POS and NER, and recent versions have switched to one-hot encoding.

**Comment by nanonaren** [comment]
Thanks, could you point out the line of code that does this? I am unable to find it. Thanks.

**Comment by hitvoice** [comment]
- create one-hot vectors: https://github.com/hitvoice/DrQA/blob/master/train.py#L281
- concatenate them to word vectors: https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L129
