### ISSUE TITLE
Adding Evidence as Database (like wikipedia )

### ISSUE THREAD

**Issue by augmen** [hitvoice/DrQA#14]
say once your model is trained and you export the model for prediction. you want to add all the evidence as database in `"id", "txt"` format.So multiple users can run the queries on the dataset for Answers .  how to add such datasets ? would we require another python script like dataset / document reader.py ?

**Comment by hitvoice** [comment]
You can treat DrQA as a separate agent and feed evidence-question pairs to it. Query handling and data storage are other independent modules of your project.

**Comment by augmen** [comment]
so its not possible to add the extra database  like evidence ?

**Comment by hitvoice** [comment]
It's possible, but out of the scope of this project. :)

**Comment by augmen** [comment]
any guidance on other repo . that we can utilise ?

**Comment by hitvoice** [comment]
I've never tried that before so there's nothing I can suggest. If you have some questions about your own project but unrelated to DrQA, please post them on more general tech forums like StackOverflow/StackExchange. A lot more experienced people will help you there.
