### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'SQuAD/meta.msgpack'

### ISSUE THREAD

**Issue by yuantw** [hitvoice/DrQA#16]
I ran download.sh and I saw two files in the SQuAD folder:
`dev-v1.1.json  train-v1.1.json`

Then I got the error when running:
`python train.py -e 40 -bs 32`

Where can I download the meta.msgpack? Thanks.

**Comment by hitvoice** [comment]
run `python prepro.py` before running `python train.py`. Please read the instructions carefully.

**Comment by yuantw** [comment]
I ran `python prepro.py` already and it took over 10 hours to complete but I didn't see the file. If it comes after running the script, I'll try again and see if that helps.

**Comment by hitvoice** [comment]
What's your spacy version? if you follow all instructions and install spacy==1.9 the prepro script should only take 1~2 minutes.

**Comment by tim5go** [comment]
@hitvoice 
It seems like the **annotate** function from SpaCy will eat up lots of memory (>10GB) 
during the data preparation process. If the machine doesn't have enough RAM, the process will turn out to be extremely slow. I guess it is what @yuantw was experiencing.

Not sure if it is a memory leakage problem for SpaCy.

**Comment by hitvoice** [comment]
@tim5go I ran the script again and indeed, the memory keeps increasing to about 10G. I didn't figure out the exact reason and I'll add a warning to ReadMe. Thanks for reporting this!

**Comment by yinfredyue** [comment]
But the problem is still here: `No such file or directory: 'SQuAD/meta.msgpack'` @hitvoice I follow strictly the steps in README.md, except chaning all `python` to `python3`
