### ISSUE TITLE
planning to implement Attend It Again paper.

### ISSUE THREAD

**Issue by anis016** [hitvoice/DrQA#19]
Hello there!

I was planning to implement the attention-again from this paper [Attend It Again](http://www.mdpi.com/2076-3417/8/3/383/pdf) on DrQA.

Basically, what Attend It again does is as follows.

> This model has two LSTM layers. In the bottom layer of LSTM, we use the traditional attention mechanisms and generate the hidden state of LSTM unit from previous hidden state and current input. Next step, we integrate the hidden state of previous LSTM unit in top layer, current input feature and the current output from the bottom layer of LSTM unit.

My plan was to take the [doc_hiddens](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L138) and the [x1_emb](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L117) and feed these to an Attention similar to [qemb_match](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L130) along with [question_hiddens](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L141) then feed this to a LSTM network similar to [doc_rnn](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L60). Later take this output and feed into start_attn and end_attn to get the start_scores and end_scores.

Can you please tell, if this will be any good to get the better F1 measure ?

**Comment by hitvoice** [comment]
It's hard to tell, but you can give it a try. The model design choice heavily depends on the dataset and it's hard to predict whether a method works in advance :)

**Comment by anis016** [comment]
Thanks for your reply!
I have a question 

[doc_hiddens](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L138) is a tensor which is of shape:

> `batch_size X number_of_sequence X doc_hidden_size`

for example: 10 X 253 X 768

The input [x1_emb](https://github.com/hitvoice/DrQA/blob/master/drqa/rnn_reader.py#L117) is of shape:

> `batch_size X number_of_sequence X embedding_size`

for example: 10 X 253 X 300

Since dimensions of these 2 tensors **doc_hiddens** and **x1_emb** are different, What I can do is put the **x1_emb** into an LSTM and get this as the same dimension as of **doc_hiddens**.
 
Then I can do a point-wise addition between **doc_hiddens** and **x1_emb** to get an unified-weighted tensor.

Can you share if point-wise addition would be a good operation in this case? or there are other better operations?
