### ISSUE TITLE
get_answer_index() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by khanhptnk** [hitvoice/DrQA#2]
running prepro.py gives error:

Traceback (most recent call last):
  File "prepro.py", line 165, in <module>
    train.answer_start, train.answer_end)])
  File "prepro.py", line 163, in <listcomp>
    zip(*[get_answer_index(a, b, c, d, e) for a, b, c, d, e in
TypeError: get_answer_index() takes 4 positional arguments but 5 were given

**Comment by hitvoice** [comment]
This seems to have been fixed in master.
