### ISSUE TITLE
Finetune against a custom dataset

### ISSUE THREAD

**Issue by vivekam101** [hitvoice/DrQA#26]
Hi Runqi Yang
Thanks for such a wonderful repo.
Quick help on how to finetune the model with a new dataset loading checkpoint from a SQUAD trained model.

**Comment by hitvoice** [comment]
Hi, 

Adding this argument `--resume /path/to/checkpoint.pt` and the code will load parameters from the checkpoint. Make sure that the model configurations are the same.
