### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EvGe22** [hitvoice/DrQA#3]
Hi, I'm new to Machine Learning and I've got a question regarding models predictions. What kind of data do i have to provide? Or even more general question. How do I actually make any predictions using this particular model?
Thanks

**Comment by hitvoice** [comment]
This project is currently a research project. It's trained and evaluated on a particular research dataset to verify the ideas from the paper and does not have an interface for prediction yet. It's worth adding one and I'll work on it later (and anyone's contribution is welcomed!). If you need a predictive model for reading comprehension right now you can refer to [https://github.com/facebookresearch/ParlAI](https://github.com/facebookresearch/ParlAI).

**Comment by EvGe22** [comment]
Thanks

**Comment by hitvoice** [comment]
The code for prediction has been added. Please refer to 'interact.py' if you want the model to make predictions.
