### ISSUE TITLE
Getting low F1 and EM scores

### ISSUE THREAD

**Issue by kushalj001** [hitvoice/DrQA#31]
I have been working independently to implement this paper and I have referred to this repo on many occasions. I started training the model but I am not getting satisfactory results. 
I am not updating the glove embeddings during training and not using the POS, ENT features. I have included `f_align_feature` however. 
Can you tell me some reasons why this might be the case? 
![image](https://user-images.githubusercontent.com/32245327/82762494-f7b0fb80-9e1e-11ea-8049-0906c95c3c28.png)

**Comment by hitvoice** [comment]
It's hard to debug a machine learning model without looking at its source code. The results are unexpected even without the POS, ENT features. I hope you have found out what went wrong.
