### ISSUE TITLE
Cant do "bash"

### ISSUE THREAD

**Issue by RSamuka** [hitvoice/DrQA#36]
When I do "bash download.sh", this happens

Error: ${REQUIRED[i]} is not installed.

I installed everything.

**Comment by hitvoice** [comment]
Did you check that these 4 are installed?
- wget
- unzip
- python3
- pip

Especially when python is installed, it should have a "python3" alias. If these are installed, you can skip the pre-download check code and just run the remaining lines.

**Comment by RSamuka** [comment]
Yes, I installed everything, I had to skip the pre-download check. Buy when I do the next comand "python train.py -e 40 -bs 32", give me this error:


File "C:\......\DrQA\train.py", line 377, in <module>
    main()
  File "C:\.......\DrQA\train.py", line 21, in main
    train, dev, dev_y, embedding, opt = load_data(vars(args))
  File "C:\........\DrQA\train.py", line 213, in load_data
    with open('SQuAD/meta.msgpack', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SQuAD/meta.msgpack'

**Comment by RSamuka** [comment]
> 
I dont have the file inside the paste.

**Comment by hitvoice** [comment]
I haven't tested my code on Windows. I've no idea what's happening. I'll reply to you maybe next week after I try my code on a windows machine.

**Comment by hitvoice** [comment]
Bash is only for Linux-based systems. Maybe you need WSL or something like that to make the script work.

**Comment by RSamuka** [comment]
I resolved it. I had to convert the encoding to utf-8.  Apreciate ur help :)

**Comment by hitvoice** [comment]
Glad to see that. :)
