### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by Backlight-SS** [hitvoice/DrQA#9]
How to use an example(question) to test this project?

**Comment by hitvoice** [comment]
This is not implemented yet. Currently, this project focuses on evaluating on SQuAD dataset only. I'll do it when I get some time. Pull requests are welcomed since it's not a difficult task.

**Comment by hitvoice** [comment]
Testing on new examples is now supported (89e68efb8d0f915f7be6cdb4baff0db3d282a5cc). Use `python interact.py` to start your interaction. See the latest version!

**Comment by Backlight-SS** [comment]
Can this project develop a demo based on web? I try to modify the project develop with facebookresearch, but i failed.
